name: Build

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: ./
      with:
        python-version: 3.8

    - name: Install required modules
      run: pip install -r requirements.txt

    - name: Linter
      run: pylint ./*.py

    - name: Unit Test
      run: pytest test/
